services:
  mongo:
    image: mongo:4.2.5
    ports:
      - '27017:27017'
  web: 
    build:
      context: app
      target: dev-envs
    stop_signal: SIGINT
    ports: 
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock